export const refranero = [
    { 'refran': 'A barriga llena, corazón contento.' },
    { 'refran': 'A buen entendedor, pocas palabras bastan.' },
    { 'refran': 'A buen hambre, no hay pan duro.' },
    { 'refran': '¡A buenas horas, mangas verdes!' },
    { 'refran': 'A burro muerto, la cebada al rabo.' },
    { 'refran': 'A caballo regalado no le mires el diente.' },
    { 'refran': 'A cada cerdo le llega su San Martín.' },
    { 'refran': 'A Dios rogando y con el mazo dando.' },
    { 'refran': 'A enemigo que huye, puente de plata.' },
    { 'refran': 'A falta de pan, buenas son tortas.' },
    { 'refran': 'A grandes males, grandes remedios.' },
    { 'refran': 'A gusto de los cocineros comen los frailes.' },
    { 'refran': 'A la arrogancia en el pedir, la virtud del no dar.' },
    { 'refran': 'A la cama no te irás sin saber una cosa más.' },
    { 'refran': 'A la tercera va la vencida.' },
    { 'refran': 'A la vejez, viruelas.' },
    { 'refran': 'A lo hecho, pecho.' },
    { 'refran': 'A mal tiempo, buena cara.' },
    { 'refran': 'A más años, más desengaños.' },
    { 'refran': 'A nadie le amarga un dulce.' },
    { 'refran': 'A otro perro con ese hueso.' },
    { 'refran': 'A palabras necias, oídos sordos.' },
    { 'refran': 'A perro flaco, todo son pulgas.' },
    { 'refran': 'A quien cuece y amasa, de todo le pasa.' },
    { 'refran': 'A quien madruga, Dios le ayuda.' },
    { 'refran': 'A quien mucho tiene, más le viene.' },
    { 'refran': 'A rey muerto, rey puesto.' },
    { 'refran': 'A río revuelto, ganancia de pescadores.' },
    { 'refran': 'A todo se acostumbra uno, menos a no comer.' },
    { 'refran': 'A un clavo ardiendo se agarra el que se está hundiendo.' },
    { 'refran': 'Abril, aguas mil.' },
    { 'refran': 'Afortunado en el juego, desafortunado en amores.' },
    { 'refran': 'Agua pasada no mueve molino.' },
    { 'refran': 'Agua que no has de beber déjala correr.' },
    { 'refran': 'Ahora adulador, mañana traidor.' },
    { 'refran': 'Al mejor cazador, se le va la liebre.' },
    { 'refran': 'Al pan, pan, y al vino, vino.' },
    { 'refran': 'Al perro flaco, todo se le vuelven pulgas.' },
    { 'refran': 'Al que Dios se la dé, San Pedro se la bendiga.' },
    { 'refran': 'Al que le pique, que se rasque.' },
    { 'refran': 'Al revés te lo digo para que me entiendas.' },
    { 'refran': 'Algo tendrá el agua cuando la bendicen.' },
    { 'refran': 'Amigo por interés no dura porque no lo es.' },
    { 'refran': 'Amor con amor se paga.' },
    { 'refran': 'Amores reñidos son los más queridos.' },
    { 'refran': 'Ande yo caliente y ríase la gente.' },
    { 'refran': 'Ante la duda, la más tetuda.' },
    { 'refran': 'Antes de hacer nada, consúltalo con la almohada.' },
    { 'refran': 'Antes de meter, prometer.' },
    { 'refran': 'Antes se coge al mentiroso que al cojo.' },
    { 'refran': 'Año de nieves, año de bienes.' },
    { 'refran': 'Aprendiz de mucho, maestro de nada.' },
    { 'refran': 'Arrieros somos, y en el camino nos encontraremos.' },
    { 'refran': 'Asno con oro, alcánzalo todo.' },
    { 'refran': 'Aunque la mona se vista de seda. mona se queda.' },
    { 'refran': 'Ave que vuela, a la cazuela.' },
    { 'refran': 'Bicho malo nunca muere.' },
    { 'refran': 'Bien está lo que bien acaba.' },
    { 'refran': 'Bien predica quien bien vive.' },
    { 'refran': 'Buey viejo, surco derecho.' },
    { 'refran': 'Caballo grande, ande o no ande.' },
    { 'refran': 'Cada cosa a su tiempo.' },
    { 'refran': 'Cada loco con su tema.' },
    { 'refran': 'Cada maestrillo tiene su librillo.' },
    { 'refran': 'Cada mochuelo a su olivo.' },
    { 'refran': 'Cada moneda tiene dos caras.' },
    { 'refran': 'Cada oveja con su pareja.' },
    { 'refran': 'Cada palo aguante su vela.' },
    { 'refran': 'Cada persona es dueña de su silencio y esclava de sus palabras.' },
    { 'refran': 'Cada uno cuenta de la feria como le va en ella.' },
    { 'refran': 'Cada uno en su casa, y Dios en la de todos.' },
    { 'refran': 'Cada uno lleva su cruz.' },
    { 'refran': 'Cada uno sabe dónde le aprieta el zapato.' },
    { 'refran': 'Cada uno se conoce por sus obras.' },
    { 'refran': 'Cada uno tiene lo que se merece.' },
    { 'refran': 'Calumnia, que algo queda.' },
    { 'refran': 'Casa con dos puertas, mala es de guardar.' },
    { 'refran': 'Casarás y amansarás.' },
    { 'refran': 'Como éramos pocos, parió la abuela.' },
    { 'refran': 'Como se vive, se muere.' },
    { 'refran': 'Como siembres, recogerás.' },
    { 'refran': 'Con el roce, nace el cariño.' },
    { 'refran': 'Con la ayuda del vecino, mató mi padre un cochino.' },
    { 'refran': 'Con la intención basta.' },
    { 'refran': 'Con la verdad se llega a todas partes.' },
    { 'refran': 'Con las glorias se olvidan las memorias.' },
    { 'refran': 'Con pan y vino, se anda el camino.' },
    { 'refran': 'Consejos vendo, y para mí no tengo.' },
    { 'refran': 'Contigo, pan y cebolla.' },
    { 'refran': 'Contra el vicio de pedir, la virtud de no dar.' },
    { 'refran': 'Contra la fortuna, no hay arte alguna.' },
    { 'refran': 'Corazón codicioso, no tiene reposo.' },
    { 'refran': 'Coser y cantar, todo es empezar.' },
    { 'refran': 'Cree el ladrón que todos son de su condición.' },
    { 'refran': 'Cría fama y échate a dormir.' },
    { 'refran': 'Cría cuervos y te sacarán los ojos.' },
    { 'refran': 'Cuando el diablo no tiene nada que hacer, mata moscas con el rabo.' },
    { 'refran': 'Cuando el gato no está, los ratones bailan.' },
    { 'refran': 'Cuando el grajo vuela bajo, hace un frío del carajo.' },
    { 'refran': 'Cuando el río suena, agua lleva.' },
    { 'refran': 'Cuando las barbas del vecino veas pelar, pon las tuyas a remojar.' },
    { 'refran': 'Cuando menos se piensa, salta la liebre.' },
    { 'refran': 'Cuando una puerta se cierra, otra se abre.' },
    { 'refran': 'Cuanto más se tiene, más se quiere.' },
    { 'refran': 'Cuanto más viejo, más pellejo.' },
    { 'refran': 'Cuidados ajenos mataron al asno.' },
    { 'refran': 'Culo veo, culo deseo.' },
    { 'refran': 'Da Dios almendras al que no tiene muelas.' },
    { 'refran': 'Dame pan, y dime tonto.' },
    { 'refran': 'Date prisa despacio, y llegarás a palacio.' },
    { 'refran': 'De aquellos polvos, vienen estos lodos.' },
    { 'refran': 'De buen vino, buen vinagre.' },
    { 'refran': 'De casta le viene al galgo el ser rabilargo.' },
    { 'refran': 'De desagradecidos está el infierno lleno.' },
    { 'refran': 'De donde no hay, no se puede sacar.' },
    { 'refran': 'De la calle vendrá, quien de tu casa te echará.' },
    { 'refran': 'De grandes cenas están las sepulturas llenas.' },
    { 'refran': 'De herrero a herrero, no pasa dinero.' },
    { 'refran': 'De ilusión también se vive.' },
    { 'refran': 'De la discusión nace la luz.' },
    { 'refran': 'De lo que no cuesta, llena la cesta.' },
    { 'refran': 'De lo que no veas, ni la mitad te creas.' },
    { 'refran': 'De lo que se come se cría.' },
    { 'refran': 'De los amigos me guarde Dios, que de los enemigos me guardo yo.' },
    { 'refran': 'De los cuarenta para arriba, no te mojes la barriga.' },
    { 'refran': 'De los escarmentados nacen los avisados.' },
    { 'refran': 'De mí te reirás, pero de mi dinero, no.' },
    { 'refran': 'De noche todos los gatos son pardos.' },
    { 'refran': 'De perdidos, al río.' },
    { 'refran': 'De tal cepa, tal vino.' },
    { 'refran': 'De tal palo, tal astilla.' },
    { 'refran': 'De todo hay en la viña del Señor.' },
    { 'refran': 'De trigo y avena, mi casa llena.' },
    { 'refran': 'De una cebolla no nace una rosa.' },
    { 'refran': 'Del agua mansa líbreme Dios, que de la brava me libraré yo.' },
    { 'refran': 'Del amor al odio hay un paso.' },
    { 'refran': 'Del árbol caído, todos hacen leña.' },
    { 'refran': 'Del dicho al hecho hay un buen trecho.' },
    { 'refran': 'Del jefe y del mulo cuanto más lejos más seguro.' },
    { 'refran': 'Del mar, el mero; de la tierra, el cordero.' },
    { 'refran': 'Del viejo, el consejo.' },
    { 'refran': 'Dentro de cien años, todos calvos.' },
    { 'refran': 'Desdichas y caminos hacen amigos.' },
    { 'refran': 'Desgracia compartida, menos sentida.' },
    { 'refran': 'Desgraciado en el juego, afortunado en amores.' },
    { 'refran': 'Desnudar un santo para vestir otro.' },
    { 'refran': 'Desnudo nací, desnudo me hallo: ni pierdo ni gano.' },
    { 'refran': 'Después de beber, cada uno dice su parecer.' },
    { 'refran': 'Después de la tempestad, viene la calma.' },
    { 'refran': 'Detrás de la cruz está el diablo.' },
    { 'refran': 'Día de Santa Lucía, mengua la noche y crece el día.' },
    { 'refran': 'Días de mucho, vísperas de nada.' },
    { 'refran': 'Dicho y hecho.' },
    { 'refran': 'Diciendo las verdades se pierden amistades.' },
    { 'refran': 'Dime con quien andas y te diré quien eres.' },
    { 'refran': 'Dime de que presumes y te diré de que careces.' },
    { 'refran': 'Dinero llama dinero.' },
    { 'refran': 'Dios aprieta pero no ahoga.' },
    { 'refran': 'Dios los cría y ellos se juntan.' },
    { 'refran': 'Divide y vencerás.' },
    { 'refran': 'Donde dije digo, digo Diego.' },
    { 'refran': 'Donde fueres, haz lo que vieres.' },
    { 'refran': 'Donde hay confianza, da asco.' },
    { 'refran': 'Donde hay patrón, no manda marinero.' },
    { 'refran': 'Donde las dan las toman.' },
    { 'refran': 'Donde manda el corazón, la cabeza tiene poco que decir.' },
    { 'refran': 'Donde menos se piensa salta la liebre.' },
    { 'refran': '¿Dónde va Vicente?, donde va la gente.' },
    { 'refran': 'Dos es compañía, tres es multitud.' },
    { 'refran': 'Dos no riñen, si uno no quiere.' },
    { 'refran': 'Dos que duermen en un colchón, se vuelven de la misma condición.' },
    { 'refran': 'El amor es ciego.' },
    { 'refran': 'El avaro, cuanto más tiene, más quiere.' },
    { 'refran': 'El bien viene andando; el mal, volando.' },
    { 'refran': 'El buen cirujano corta por lo sano.' },
    { 'refran': 'El buen paño en el arca se vende.' },
    { 'refran': 'El buen perfume se vende en frasco pequeño.' },
    { 'refran': 'El buey suelto, bien se lame.' },
    { 'refran': 'El casado, casa quiere.' },
    { 'refran': 'El comer y el rascar, todo es empezar.' },
    { 'refran': 'El dinero hace caballero.' },
    { 'refran': 'El fin justifica los medios.' },
    { 'refran': 'El fruto prohibido es el más apetecido.' },
    { 'refran': 'El gato escaldado, del agua fría huye.' },
    { 'refran': 'El hábito no hace al monje.' },
    { 'refran': 'El hambre aguza el ingenio.' },
    { 'refran': 'El hambre es muy mala consejera.' },
    { 'refran': 'El hombre es el único animal que tropieza dos veces en la misma piedra.' },
    { 'refran': 'El hombre propone, y Dios dispone.' },
    { 'refran': 'El hombre y el oso, cuanto más feo, más hermoso.' },
    { 'refran': 'El huésped y el pez, a los tres días hiede.' },
    { 'refran': 'El invierno no es pasado mientras abril no es terminado.' },
    { 'refran': 'El llanto, sobre el difunto.' },
    { 'refran': 'El lloro de la mujer, no es de creer.' },
    { 'refran': 'El mejor escribano echa un borrón.' },
    { 'refran': 'El mentiroso ha de ser memorioso.' },
    { 'refran': 'El muerto al hoyo y el vivo al bollo.' },
    { 'refran': 'El mundo es un pañuelo.' },
    { 'refran': 'El ocio no quede impune; quien no trabaje, que ayune.' },
    { 'refran': 'El ojo del amo engorda el caballo.' },
    { 'refran': 'El perro del hortelano, ni come ni deja comer al amo.' },
    { 'refran': 'El pez grande se come al chico.' },
    { 'refran': 'El poeta nace, no se hace.' },
    { 'refran': 'El que a buen árbol se arrima, buena sombra le cobija.' },
    { 'refran': 'El que a hierro mata, a hierro muere.' },
    { 'refran': 'El que al cielo escupe en la cara le cae.' },
    { 'refran': 'El que algo quiere, algo le cuesta.' },
    { 'refran': 'El que avisa no es traidor.' },
    { 'refran': 'El que busca halla.' },
    { 'refran': 'El que calla, otorga.' },
    { 'refran': 'El que espera, desespera.' },
    { 'refran': 'El que esté libre de pecado, que tire la primera piedra.' },
    { 'refran': 'El que fue a Sevilla perdió su silla.' },
    { 'refran': 'El que guarda, siempre tiene.' },
    { 'refran': 'El que la sigue, la consigue.' },
    { 'refran': 'El que mucho corre, pronto para.' },
    { 'refran': 'El que mucho habla, mucho yerra.' },
    { 'refran': 'El que mucho ofrece, poco da.' },
    { 'refran': 'El que no llora, no mama.' },
    { 'refran': 'El que no quiera polvo, que no vaya a la era.' },
    { 'refran': 'El que no se consuela, es porque no quiere.' },
    { 'refran': 'El que no trabaja, no come.' },
    { 'refran': 'El que parte y reparte, se queda con la mejor parte.' },
    { 'refran': 'El que pega primero, pega dos veces.' },
    { 'refran': 'El que quiera peces que se moje el culo.' },
    { 'refran': 'El que ríe el último, ríe mejor.' },
    { 'refran': 'El que rompe, paga.' },
    { 'refran': 'El que se excusa, se acusa.' },
    { 'refran': 'El que se pica, ajos come.' },
    { 'refran': 'El que siembra viento, cosecha tempestades.' },
    { 'refran': 'El que tiene boca, se equivoca.' },
    { 'refran': 'El que tiene padrino se bautiza.' },
    { 'refran': 'El que tiene un tío en Alcalá, ni tiene tío ni tiene ná.' },
    { 'refran': 'El que tuvo, retuvo.' },
    { 'refran': 'El que venga detrás, que arree.' },
    { 'refran': 'El que vive de favores, sirve a muchos señores.' },
    { 'refran': 'El saber no ocupa lugar.' },
    { 'refran': 'El sabio siempre quiere aprender, el ignorante siempre quiere enseñar.' },
    { 'refran': 'El tiempo es oro.' },
    { 'refran': 'El tiempo lo dirá.' },
    { 'refran': 'El tiempo perdido no se recupera.' },
    { 'refran': 'El tiempo pone a cada uno en su sitio.' },
    { 'refran': 'El tiempo todo lo cura.' },
    { 'refran': 'En boca cerrada no entran moscas.' },
    { 'refran': 'En casa del herrero, cuchillo de palo.' },
    { 'refran': 'En casa del pobre, dura poco la alegría.' },
    { 'refran': 'En el país de los ciegos, el tuerto es el rey.' },
    { 'refran': 'En febrero busca la sombra el perro.' },
    { 'refran': 'En la guerra y en el amor, todo vale.' },
    { 'refran': 'En la tardanza está el peligro.' },
    { 'refran': 'En la variedad está el gusto.' },
    { 'refran': 'En martes, ni te cases ni te embarques.' },
    { 'refran': 'En tiempo de higos no hay amigos.' },
    { 'refran': 'En todas partes cuecen habas.' },
    { 'refran': 'Encender una vela a Dios y otra al diablo.' },
    { 'refran': 'Entre col y col, lechuga.' },
    { 'refran': 'Entre dos amigos, un notario y dos testigos.' },
    { 'refran': 'Entre todos la mataron y ella sola se murió.' },
    { 'refran': 'Es buena noticia el que no las haya.' },
    { 'refran': 'Es de bien nacidos ser agradecidos.' },
    { 'refran': 'Es la gota que desborda el vaso.' },
    { 'refran': 'Es peor el remedio que la enfermedad.' },
    { 'refran': 'Escoba nueva barre bien.' },
    { 'refran': 'Gallina vieja hace buen caldo.' },
    { 'refran': 'Gallo que no canta, algo tiene en la garganta.' },
    { 'refran': 'Gato con guantes no caza ratones.' },
    { 'refran': 'Gato escaldado, del agua fría huye.' },
    { 'refran': 'Genio y figura, hasta la sepultura.' },
    { 'refran': 'Gota a gota, se llena la bota.' },
    { 'refran': 'Gusta lo ajeno más por ajeno que por bueno.' },
    { 'refran': 'Hablando del rey de Roma, por la puerta asoma.' },
    { 'refran': 'Hablando se entiende la gente.' },
    { 'refran': 'Habló el buey y dijo mu.' },
    { 'refran': 'Haciendo y deshaciendo se va aprendiendo.' },
    { 'refran': 'Hambre que espera hartura, no es hambre pura.' },
    { 'refran': 'Hasta el cuarenta de mayo no te quites el sayo.' },
    { 'refran': 'Hasta el rabo, todo es toro.' },
    { 'refran': 'Hay más días que longanizas.' },
    { 'refran': 'Haz bien y no mires a quien.' },
    { 'refran': 'Hijo sin dolor, madre sin amor.' },
    { 'refran': 'Hombre prevenido, vale por dos.' },
    { 'refran': 'Hoy por ti, mañana por mí.' },
    { 'refran': 'Huir del fuego para caer en las brasas.' },
    { 'refran': 'Ir por lana y volver trasquilado.' },
    { 'refran': 'Jaula nueva, pájaro muerto.' },
    { 'refran': 'Juan Palomo, yo me lo guiso y yo me lo como.' },
    { 'refran': 'Juego y bebida, casa perdida.' },
    { 'refran': 'La arruga es bella.' },
    { 'refran': 'La ausencia causa olvido.' },
    { 'refran': 'La avaricia rompe el saco.' },
    { 'refran': 'La cabra siempre tira al monte.' },
    { 'refran': 'La cara es el espejo del alma.' },
    { 'refran': 'La caridad bien entendida empieza por uno mismo.' },
    { 'refran': 'La casa se arruina por la cocina.' },
    { 'refran': 'La costumbre hace ley.' },
    { 'refran': 'La curiosidad mató al gato.' },
    { 'refran': 'La ensalada, poco vinagre y bien aceitada.' },
    { 'refran': 'La esperanza es lo último que se pierde.' },
    { 'refran': 'La excepción confirma la regla.' },
    { 'refran': 'La experiencia es la madre de la ciencia.' },
    { 'refran': 'La fe mueve montañas.' },
    { 'refran': 'La gallina de mi vecina más huevos pone que la mía.' },
    { 'refran': 'La hermosura poco dura.' },
    { 'refran': 'La ignorancia de la ley no excusa su cumplimiento.' },
    { 'refran': 'La intención es lo que vale.' },
    { 'refran': 'La juventud tiene la fuerza y la vejez la prudencia.' },
    { 'refran': 'La lengua no tiene hueso, pero corta lo más grueso.' },
    { 'refran': 'La letra con sangre entra.' },
    { 'refran': 'La ley del embudo, para mí lo ancho y para ti lo agudo.' },
    { 'refran': 'La manzana podrida pierde a su compañía.' },
    { 'refran': 'La mejor palabra siempre es la que queda por decir.' },
    { 'refran': 'La mejor salsa, el apetito.' },
    { 'refran': 'La mujer del César, además de ser honesta, debe parecerlo.' },
    { 'refran': 'La mujer y el oro, lo pueden todo.' },
    { 'refran': 'La mujer y el vino sacan al hombre de tino.' },
    { 'refran': 'La música amansa las fieras.' },
    { 'refran': 'La ocasión la pintan calva.' },
    { 'refran': 'La palabra es plata y el silencio es oro.' },
    { 'refran': 'La palabra que sale de la boca, nunca torna.' },
    { 'refran': 'La peor gallina es la que más cacarea.' },
    { 'refran': 'La perseverancia todo lo alcanza.' },
    { 'refran': 'La primavera la sangre altera.' },
    { 'refran': 'La procesión va por dentro.' },
    { 'refran': 'La realidad supera la ficción.' },
    { 'refran': 'La respuesta mansa la ira quebranta.' },
    { 'refran': 'La suegra y el doctor, cuanto más lejos, mejor.' },
    { 'refran': 'La suerte de la fea, la bonita la desea.' },
    { 'refran': 'La suerte está echada.' },
    { 'refran': 'La unión hace la fuerza.' },
    { 'refran': 'La venganza es un plato que se sirve frío.' },
    { 'refran': 'La verdad es amarga.' },
    { 'refran': 'La vida no es un camino de rosas.' },
    { 'refran': 'La viuda rica hace que llora y repica.' },
    { 'refran': 'Las apariencias engañan.' },
    { 'refran': 'Las armas de fuego, cuanto más lejos, mejor.' },
    { 'refran': 'Las comparaciones son odiosas.' },
    { 'refran': 'Las cosas de palacio van despacio.' },
    { 'refran': 'Las cuentas claras, y el chocolate espeso.' },
    { 'refran': 'Las desgracias nunca vienen solas.' },
    { 'refran': 'Las madres hacendosas hacen las hijas perezosas.' },
    { 'refran': 'Las malas noticias vuelan.' },
    { 'refran': 'Las palabras vuelan, y lo escrito permanece.' },
    { 'refran': 'Las paredes oyen.' },
    { 'refran': 'Las prisas nunca son buenas.' },
    { 'refran': 'Libro prestado, libro perdido.' },
    { 'refran': 'Lo barato sale caro.' },
    { 'refran': 'Lo bien hecho, bien parece.' },
    { 'refran': 'Lo bueno poco dura.' },
    { 'refran': 'Lo bueno, si breve, dos veces bueno.' },
    { 'refran': 'Lo comido por lo servido.' },
    { 'refran': 'Lo cortés no quita lo valiente.' },
    { 'refran': 'Lo fiado, rara vez pagado.' },
    { 'refran': 'Lo olvidado, ni agradecido ni pagado.' },
    { 'refran': 'Lo prometido es deuda.' },
    { 'refran': 'Lo que a unos mata, a otros sana.' },
    { 'refran': 'Lo que bien empieza, bien acaba.' },
    { 'refran': 'Lo que de noche se hace, a la mañana parece.' },
    { 'refran': 'Lo que en los libros no está, la vida te lo enseñará.' },
    { 'refran': 'Lo que es moda no incomoda.' },
    { 'refran': 'Lo que mucho vale, mucho cuesta.' },
    { 'refran': 'Lo que no has de comer, déjalo cocer.' },
    { 'refran': 'Lo que no mata, engorda.' },
    { 'refran': 'Lo que no se comienza, nunca se acaba.' },
    { 'refran': 'Lo que no se llevan los ladrones, aparece por los rincones.' },
    { 'refran': 'Lo que no va en lágrimas va en suspiros.' },
    { 'refran': 'Lo que otro suda, a mí poco me dura.' },
    { 'refran': 'Lo que poco cuesta, poco se aprecia.' },
    { 'refran': 'Lo que se aprende en la cuna, siempre dura.' },
    { 'refran': 'Lo que sea sonará.' },
    { 'refran': 'Los amigos de mis amigos son mis amigos.' },
    { 'refran': 'Los amigos de mis amigos son mis amigos.' },
    { 'refran': 'Los años no pasan en balde.' },
    { 'refran': 'Los árboles no dejan ver el bosque.' },
    { 'refran': 'Los celos son malos consejeros.' },
    { 'refran': 'Los duelos con pan, son menos.' },
    { 'refran': 'Los huéspedes mucho gusto dan, pero cuando se van.' },
    { 'refran': 'Los malos tragos hay que pasarlos pronto.' },
    { 'refran': 'Los niños y los locos dicen las verdades.' },
    { 'refran': 'Los toros se ven mejor desde la barrera.' },
    { 'refran': 'Los trapos sucios se lavan en casa.' },
    { 'refran': 'Mal de muchos, consuelo de tontos.' },
    { 'refran': 'Mañana será otro día.' },
    { 'refran': 'Manitas que no dais, ¿qué esperáis?' },
    { 'refran': 'Manos frías, corazón caliente.' },
    { 'refran': 'Marido celoso no tiene reposo.' },
    { 'refran': 'Marzo ventoso y abril lluvioso sacan a mayo florido y hermoso.' },
    { 'refran': 'Más hace el que quiere que el que puede.' },
    { 'refran': 'Más discurre un hambriento que cien letrados.' },
    { 'refran': 'Más sabe el diablo por viejo que por diablo.' },
    { 'refran': 'Más vale caer en gracia que ser gracioso.' },
    { 'refran': 'Más vale estar solo que mal acompañado.' },
    { 'refran': 'Más vale gastar en pan que en botica.' },
    { 'refran': 'Más vale llegar a tiempo que rondar un año.' },
    { 'refran': 'Más vale malo conocido que lo bueno por conocer.' },
    { 'refran': 'Más vale maña que fuerza.' },
    { 'refran': 'Más vale pájaro en mano que ciento volando.' },
    { 'refran': 'Más vale prevenir que curar.' },
    { 'refran': 'Más vale ser arriero que borrico.' },
    { 'refran': 'Más vale tarde que nunca.' },
    { 'refran': 'Más vale tener que desear.' },
    { 'refran': 'Más vale tuerto que ciego.' },
    { 'refran': 'Más vale un mal arreglo que un buen pleito.' },
    { 'refran': 'Más ven cuatro ojos que dos.' },
    { 'refran': 'Mejor dar que recibir.' },
    { 'refran': 'Mucho ruido y pocas nueces.' },
    { 'refran': 'Muchos son los llamados y pocos los escogidos.' },
    { 'refran': 'Muerto el perro, se acabó la rabia.' },
    { 'refran': 'Nadie da lo que no tiene.' },
    { 'refran': 'Nadie es profeta en su tierra.' },
    { 'refran': 'Nadie escarmienta en cabeza ajena.' },
    { 'refran': 'Nadie se acuerda de Santa Bárbara hasta que truena.' },
    { 'refran': 'Nadie se meta donde no le llamen.' },
    { 'refran': 'Nadie tira piedras a su tejado.' },
    { 'refran': 'Ni pidas a quien pidió, ni sirvas a quien sirvió.' },
    { 'refran': 'Ni son todos los que están, ni están todos los que son.' },
    { 'refran': 'Ni tanto ni tan calvo.' },
    { 'refran': 'Ningún jorobado ve su joroba.' },
    { 'refran': 'Ninguno escarmienta en cabeza ajena.' },
    { 'refran': 'No basta ser bueno sino parecerlo.' },
    { 'refran': 'No cantan dos gallos en un gallinero.' },
    { 'refran': 'No cantes gloria hasta el fin de la victoria.' },
    { 'refran': 'No cojas la pera hasta que esté madura.' },
    { 'refran': 'No comer por haber comido no es tiempo perdido.' },
    { 'refran': 'No con quien naces sino con quien paces.' },
    { 'refran': 'No dejes para mañana lo que puedas hacer hoy.' },
    { 'refran': 'No echéis margaritas a los cerdos.' },
    { 'refran': 'No es lo mismo ser que parecer.' },
    { 'refran': 'No es más limpio el que más limpia, sino el que menos ensucia.' },
    { 'refran': 'No es más rico quien más tiene sino el que menos necesita.' },
    { 'refran': 'No es oro todo lo que reluce.' },
    { 'refran': 'No es tan fiero el león como lo pintan.' },
    { 'refran': 'No hay don sin din.' },
    { 'refran': 'No hay enemigo pequeño.' },
    { 'refran': 'No hay harina sin salvado.' },
    { 'refran': 'No hay mal que cien años dure.' },
    { 'refran': 'No hay mal que por bien no venga.' },
    { 'refran': 'No hay mayor desprecio que no hacer aprecio.' },
    { 'refran': 'No hay peor ciego que el que no quiere ver.' },
    { 'refran': 'No hay peor sordo que el que no quiere oír.' },
    { 'refran': 'No hay primavera sin flores ni verano sin calores.' },
    { 'refran': 'No hay que empezar la casa por el tejado.' },
    { 'refran': 'No hay que fiarse de las apariencias.' },
    { 'refran': 'No hay que vender la piel del oso antes de haberlo cazado.' },
    { 'refran': 'No hay regla sin excepción.' },
    { 'refran': 'No hay rosa sin espinas.' },
    { 'refran': 'No hay tonto que no se tenga por listo.' },
    { 'refran': 'No muerdas la mano que te da de comer.' },
    { 'refran': 'No ofende quien quiere sino quien puede.' },
    { 'refran': 'No por mucho madrugar, amanece más temprano.' },
    { 'refran': 'No quieres caldo, pues toma tres tazas.' },
    { 'refran': 'No sabes lo que tienes hasta que lo pierdes.' },
    { 'refran': 'No se acuerda el cura de cuando fue sacristán.' },
    { 'refran': 'No se ganó Zamora en una hora.' },
    { 'refran': 'No se hizo la miel para la boca del asno.' },
    { 'refran': 'No se puede estar en misa y repicando.' },
    { 'refran': 'No se puede hacer tortilla sin romper los huevos.' },
    { 'refran': 'No sólo de pan vive el hombre.' },
    { 'refran': 'No te cierres una puerta, si no has abierto otra.' },
    { 'refran': 'No te rías del mal de vecino, que el tuyo viene de camino.' },
    { 'refran': 'No tires piedras sobre tu tejado.' },
    { 'refran': 'No todo el monte es orégano.' },
    { 'refran': 'No vendas la piel de oso antes de haberlo cazado.' },
    { 'refran': 'Nuestro gozo en un pozo.' },
    { 'refran': 'Nunca digas de este agua no beberé.' },
    { 'refran': 'Nunca es tarde si la dicha es buena.' },
    { 'refran': 'Nunca falta un roto para un descosido.' },
    { 'refran': 'Nunca llueve a gusto de todos.' },
    { 'refran': 'Nunca segundas partes fueron buenas.' },
    { 'refran': 'Obras son amores, que no buenas razones.' },
    { 'refran': 'Ojo por ojo, diente por diente.' },
    { 'refran': 'Ojos que no ven, corazón que no siente.' },
    { 'refran': 'Otro vendrá que bueno me hará.' },
    { 'refran': 'Oveja que bala, bocado que pierde.' },
    { 'refran': 'Palos con gusto no duelen.' },
    { 'refran': 'Pan con pan, comida de tontos.' },
    { 'refran': 'Pan para hoy, y hambre para mañana.' },
    { 'refran': 'Para ese viaje no se necesitan alforjas.' },
    { 'refran': 'Para muestra, un botón.' },
    { 'refran': 'Paso a paso se va lejos.' },
    { 'refran': 'Pelillos a la mar.' },
    { 'refran': 'Perro ladrador, poco mordedor.' },
    { 'refran': 'Pesar ajeno, no quita el sueño.' },
    { 'refran': 'Piensa el ladrón que todos son de su condición.' },
    { 'refran': 'Piensa mal y acertarás.' },
    { 'refran': 'Pleitos tengas y los ganes.' },
    { 'refran': 'Poco a poco se llega antes.' },
    { 'refran': 'Pocos y mal avenidos.' },
    { 'refran': 'Poderoso caballero es don dinero.' },
    { 'refran': 'Por dinero baila el perro.' },
    { 'refran': 'Por el canto se conoce el pájaro.' },
    { 'refran': 'Por el hilo se saca el ovillo.' },
    { 'refran': 'Por el interés, te quiero Andrés.' },
    { 'refran': 'Por la boca muere el pez.' },
    { 'refran': 'Por San Blas la cigüeña verás.' },
    { 'refran': 'Por sus frutos los conoceréis.' },
    { 'refran': 'Por un clavo se pierde una herradura.' },
    { 'refran': 'Por un oído me entra y por otro me sale.' },
    { 'refran': 'Por un perro que maté, mataperros me llamaron.' },
    { 'refran': 'Preguntando se va a Roma.' },
    { 'refran': 'Primero es la obligación que la devoción.' },
    { 'refran': 'Que cada palo aguante su vela.' },
    { 'refran': 'Querer es poder.' },
    { 'refran': 'Quien a buen árbol se arrima buena sombra le cobija.' },
    { 'refran': 'Quien a hierro mata, a hierro muere.' },
    { 'refran': 'Quien bien ata, bien desata.' },
    { 'refran': 'Quien bien siembra bien recoge.' },
    { 'refran': 'Quien bien te quiere, te hará llorar.' },
    { 'refran': 'Quien busca halla.' },
    { 'refran': 'Quien calla otorga.' },
    { 'refran': 'Quien con fuego juega se quema.' },
    { 'refran': 'Quien con lobos anda, a aullar se enseña.' },
    { 'refran': 'Quien con niños se acuesta mojado amanece.' },
    { 'refran': 'Quien da pan a perro ajeno pierde pan y pierde perro.' },
    { 'refran': 'Quien da primero, da dos veces' },
    { 'refran': 'Quien de joven no trabaja de viejo duerme en la paja.' },
    { 'refran': 'Quien enferma de locura, no tiene cura.' },
    { 'refran': 'Quien esté libre de culpa que tire la primera piedra.' },
    { 'refran': 'Quien guarda, halla.' },
    { 'refran': 'Quien hace lo que puede no está obligado a más.' },
    { 'refran': 'Quien hizo la ley hizo la trampa.' },
    { 'refran': 'Quien llega tarde, ni oye misa ni come carne.' },
    { 'refran': 'Quien mal anda mal acaba.' },
    { 'refran': 'Quien más pone, más pierde.' },
    { 'refran': 'Quien más tiene, más quiere.' },
    { 'refran': 'Quien mucho abarca poco aprieta.' },
    { 'refran': 'Quien mucho duerme, poco aprende.' },
    { 'refran': 'Quien nace lechón, muere cochino.' },
    { 'refran': 'Quien no barbecha no cosecha.' },
    { 'refran': 'Quien no se arriesga, no pasa la mar.' },
    { 'refran': 'Quien no siembra no recoge.' },
    { 'refran': 'Quien no te conoce que te compre.' },
    { 'refran': 'Quien no tenga cabeza, que tenga pies.' },
    { 'refran': 'Quien no tiene padrino, no se bautiza.' },
    { 'refran': 'Quien paga descansa.' },
    { 'refran': 'Quien paga manda.' },
    { 'refran': 'Quien tiene boca se equivoca.' },
    { 'refran': 'Quien predica en el desierto pierde el sermón.' },
    { 'refran': 'Quien roba a un ladrón, tiene cien años de perdón.' },
    { 'refran': 'Quien se pica ajos come.' },
    { 'refran': 'Quien siembra vientos recoge tempestades.' },
    { 'refran': 'Quien tiene un amigo tiene un tesoro.' },
    { 'refran': 'Quien todo lo quiere, todo lo pierde.' },
    { 'refran': 'Rectificar es de sabios.' },
    { 'refran': 'Renovarse o morir.' },
    { 'refran': 'Reunión de pastores, oveja muerta.' },
    { 'refran': 'Resultó peor el remedio que la enfermedad.' },
    { 'refran': 'Salir de Guatemala y entrar en Guatepeor.' },
    { 'refran': 'Santa Rita, Rita, lo que se da no se quita.' },
    { 'refran': 'Sarna con gusto no pica.' },
    { 'refran': 'Se dice el pecado pero no el pecador.' },
    { 'refran': 'Se dice el pecado pero no el pecador.' },
    { 'refran': 'Si dices las verdades, pierdes las amistades.' },
    { 'refran': 'Si hay trato, pueden ser amigos perro y gato.' },
    { 'refran': 'Si la envidia fuera tiña, ¡cuántos tiñosos habría!.' },
    { 'refran': 'Si la montaña no va a Mahoma, Mahoma va a la montaña.' },
    { 'refran': 'Si no puedes con tu enemigo, únete a él.' },
    { 'refran': 'Si no quieres una taza, taza y media.' },
    { 'refran': 'Si no te envidia nadie, poco vales.' },
    { 'refran': 'Si te mandare tu mujer arrojarte de un tajo, ruega a Dios que sea bajo.' },
    { 'refran': 'Siempre sale a hablar quien tiene por qué callar.' },
    { 'refran': 'Sobre gustos no hay nada escrito.' },
    { 'refran': 'Tal amo, tal criado.' },
    { 'refran': 'Tanto tienes, tanto vales.' },
    { 'refran': 'Tanto va el cántaro a la fuente que al final se rompe.' },
    { 'refran': 'Tirar la piedra y esconder la mano.' },
    { 'refran': 'Todo se pega menos la hermosura.' },
    { 'refran': 'Todo tiene remedio menos la muerte.' },
    { 'refran': 'Tras cornudo, apaleado.' },
    { 'refran': 'Tripa vacía, corazón sin alegría.' },
    { 'refran': 'Un clavo saca otro clavo.' },
    { 'refran': 'Un grano no hace granero, pero ayuda al compañero.' },
    { 'refran': 'Una aguja en un pajar, es difícil de encontrar.' },
    { 'refran': 'Una cosa es predicar y otra dar trigo.' },
    { 'refran': 'Una imagen vale más que mil palabras.' },
    { 'refran': 'Una mano lava a la otra, y ambas la cara.' },
    { 'refran': 'Una vez te casarás y mil te arrepentirás.' },
    { 'refran': 'Unos lo siembran, y otros lo siegan.' },
    { 'refran': 'Unos nacen con estrella y otros estrellados.' },
    { 'refran': 'Unos por otros, la casa sin barrer.' },
    { 'refran': 'Unos tanto y otros tan poco.' },
    { 'refran': 'Unos tienen la fama, y otros cardan la lana.' },
    { 'refran': 'Uso hace maestro.' },
    { 'refran': 'Vemos la paja en el ojo ajeno, y no vemos la viga en el nuestro.' },
    { 'refran': 'Vísteme despacio que tengo prisa.' },
    { 'refran': 'Zapatero, a tus zapatos.' },
    { 'refran': 'Zurrón de mendigo, nunca bien henchido.' }
]